# Generated by Django 3.0.3 on 2020-02-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controlmedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('edad', models.CharField(max_length=3)),
                ('peso', models.CharField(max_length=3)),
                ('talla', models.CharField(max_length=3)),
                ('pd', models.CharField(max_length=3)),
                ('hierro', models.CharField(max_length=3)),
                ('Observaciones', models.CharField(max_length=3)),
                ('proximocontrol', models.DateTimeField()),
            ],
        ),
    ]
