# Generated by Django 3.0.3 on 2020-03-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='hijos',
            field=models.ManyToManyField(blank=True, null=True, through='carnets.Tipo_de_tutor', to='carnets.Nino'),
        ),
    ]
