# Generated by Django 3.0.3 on 2020-02-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlmedico',
            name='Observaciones',
        ),
        migrations.AddField(
            model_name='controlmedico',
            name='observaciones',
            field=models.CharField(default=180, max_length=220),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlmedico',
            name='created_at',
            field=models.DateField(),
        ),
    ]
