# Generated by Django 3.0.3 on 2020-03-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0002_auto_20200320_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_medico',
            name='hierro',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='control_medico',
            name='vit_D',
            field=models.CharField(max_length=30),
        ),
    ]
