# Generated by Django 3.0.3 on 2020-02-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0002_auto_20200219_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmedico',
            name='observaciones',
            field=models.TextField(),
        ),
    ]
