# Generated by Django 3.0.3 on 2020-02-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0003_auto_20200219_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Controlmedico',
            new_name='Control',
        ),
    ]
